// Generated by gencpp from file turtlesim/GetCircles.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETCIRCLES_H
#define TURTLESIM_MESSAGE_GETCIRCLES_H

#include <ros/service_traits.h>


#include <turtlesim/GetCirclesRequest.h>
#include <turtlesim/GetCirclesResponse.h>


namespace turtlesim
{

struct GetCircles
{

typedef GetCirclesRequest Request;
typedef GetCirclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCircles
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::GetCircles > {
  static const char* value()
  {
    return "2b1b1441bc75b4f59372da8dedbed3bb";
  }

  static const char* value(const ::turtlesim::GetCircles&) { return value(); }
};

template<>
struct DataType< ::turtlesim::GetCircles > {
  static const char* value()
  {
    return "turtlesim/GetCircles";
  }

  static const char* value(const ::turtlesim::GetCircles&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::GetCirclesRequest> should match 
// service_traits::MD5Sum< ::turtlesim::GetCircles > 
template<>
struct MD5Sum< ::turtlesim::GetCirclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetCircles >::value();
  }
  static const char* value(const ::turtlesim::GetCirclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetCirclesRequest> should match 
// service_traits::DataType< ::turtlesim::GetCircles > 
template<>
struct DataType< ::turtlesim::GetCirclesRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetCircles >::value();
  }
  static const char* value(const ::turtlesim::GetCirclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::GetCirclesResponse> should match 
// service_traits::MD5Sum< ::turtlesim::GetCircles > 
template<>
struct MD5Sum< ::turtlesim::GetCirclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetCircles >::value();
  }
  static const char* value(const ::turtlesim::GetCirclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetCirclesResponse> should match 
// service_traits::DataType< ::turtlesim::GetCircles > 
template<>
struct DataType< ::turtlesim::GetCirclesResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetCircles >::value();
  }
  static const char* value(const ::turtlesim::GetCirclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETCIRCLES_H
