// Generated by gencpp from file turtlesim/RemoveCircle.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_REMOVECIRCLE_H
#define TURTLESIM_MESSAGE_REMOVECIRCLE_H

#include <ros/service_traits.h>


#include <turtlesim/RemoveCircleRequest.h>
#include <turtlesim/RemoveCircleResponse.h>


namespace turtlesim
{

struct RemoveCircle
{

typedef RemoveCircleRequest Request;
typedef RemoveCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveCircle
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::RemoveCircle > {
  static const char* value()
  {
    return "33e097ebc19ab7d381da8cb765933cf3";
  }

  static const char* value(const ::turtlesim::RemoveCircle&) { return value(); }
};

template<>
struct DataType< ::turtlesim::RemoveCircle > {
  static const char* value()
  {
    return "turtlesim/RemoveCircle";
  }

  static const char* value(const ::turtlesim::RemoveCircle&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::RemoveCircleRequest> should match 
// service_traits::MD5Sum< ::turtlesim::RemoveCircle > 
template<>
struct MD5Sum< ::turtlesim::RemoveCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::RemoveCircle >::value();
  }
  static const char* value(const ::turtlesim::RemoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::RemoveCircleRequest> should match 
// service_traits::DataType< ::turtlesim::RemoveCircle > 
template<>
struct DataType< ::turtlesim::RemoveCircleRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::RemoveCircle >::value();
  }
  static const char* value(const ::turtlesim::RemoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::RemoveCircleResponse> should match 
// service_traits::MD5Sum< ::turtlesim::RemoveCircle > 
template<>
struct MD5Sum< ::turtlesim::RemoveCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::RemoveCircle >::value();
  }
  static const char* value(const ::turtlesim::RemoveCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::RemoveCircleResponse> should match 
// service_traits::DataType< ::turtlesim::RemoveCircle > 
template<>
struct DataType< ::turtlesim::RemoveCircleResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::RemoveCircle >::value();
  }
  static const char* value(const ::turtlesim::RemoveCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_REMOVECIRCLE_H
