// Generated by gencpp from file turtlesim/SpawnCircle.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_SPAWNCIRCLE_H
#define TURTLESIM_MESSAGE_SPAWNCIRCLE_H

#include <ros/service_traits.h>


#include <turtlesim/SpawnCircleRequest.h>
#include <turtlesim/SpawnCircleResponse.h>


namespace turtlesim
{

struct SpawnCircle
{

typedef SpawnCircleRequest Request;
typedef SpawnCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnCircle
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::SpawnCircle > {
  static const char* value()
  {
    return "b1a607047a224654150e8bf2b094afd3";
  }

  static const char* value(const ::turtlesim::SpawnCircle&) { return value(); }
};

template<>
struct DataType< ::turtlesim::SpawnCircle > {
  static const char* value()
  {
    return "turtlesim/SpawnCircle";
  }

  static const char* value(const ::turtlesim::SpawnCircle&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::SpawnCircleRequest> should match 
// service_traits::MD5Sum< ::turtlesim::SpawnCircle > 
template<>
struct MD5Sum< ::turtlesim::SpawnCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SpawnCircle >::value();
  }
  static const char* value(const ::turtlesim::SpawnCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SpawnCircleRequest> should match 
// service_traits::DataType< ::turtlesim::SpawnCircle > 
template<>
struct DataType< ::turtlesim::SpawnCircleRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SpawnCircle >::value();
  }
  static const char* value(const ::turtlesim::SpawnCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::SpawnCircleResponse> should match 
// service_traits::MD5Sum< ::turtlesim::SpawnCircle > 
template<>
struct MD5Sum< ::turtlesim::SpawnCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SpawnCircle >::value();
  }
  static const char* value(const ::turtlesim::SpawnCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SpawnCircleResponse> should match 
// service_traits::DataType< ::turtlesim::SpawnCircle > 
template<>
struct DataType< ::turtlesim::SpawnCircleResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SpawnCircle >::value();
  }
  static const char* value(const ::turtlesim::SpawnCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_SPAWNCIRCLE_H
